# Generated by Django 5.2.4 on 2025-07-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Slider Image')),
                ('alt_text', models.CharField(max_length=255, verbose_name='Alt Text')),
                ('heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('subheading', models.TextField(verbose_name='Subheading')),
                ('button_text', models.CharField(max_length=100, verbose_name='Button Text')),
                ('button_url_name', models.URLField(help_text='Enter the URL Address', max_length=100, verbose_name='URL Address')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Home Slider',
                'verbose_name_plural': 'Home Sliders',
                'ordering': ['order'],
            },
        ),
    ]
