# Generated by Django 5.2.4 on 2025-07-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_hover',
            field=models.BooleanField(default=False),
        ),
    ]
