# Generated by Django 5.2.4 on 2025-07-21 22:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimage_is_hover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Color hex code (e.g., #FF0000)', image_field=None, max_length=25, samples=None, verbose_name='Color Code'),
        ),
    ]
