# Generated by Django 5.2.4 on 2025-07-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_total_items_field_cart_total_price_field'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product', 'color'), name='unique_main_image_per_product_color'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_hover', True)), fields=('product', 'color'), name='unique_hover_image_per_product_color'),
        ),
    ]
