# Generated by Django 5.2.4 on 2025-07-25 14:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productimage_unique_main_image_per_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add size chart content here (HTML supported)', null=True),
        ),
    ]
