# Generated by Django 5.2.4 on 2025-07-26 01:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_return',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Add Delivery and return policy (HTML supported)', null=True),
        ),
    ]
